### ISSUE TITLE
Detect when "files were modified by this hook"

### ISSUE THREAD

**Issue by iCarossio** [Escape-Technologies/mookme#1]
Some hooks such as `yapf`, `docformatter`, or `eslint` can either return a non-0 exit code or modify files in place.

```shell
yapf -rd . # return non-0 exit code
yapf -ri . # modifies in place
yapf -rid . # 'i' and 'd' are incompatible options.
```

For each hook, it would be great to use the "modify in-place" option and detect if any files have been modified by this hook (by checking `git diff` at the end of each hook for instance) in order to either:
1) say the hook has failed and manually git add the difference
2) or automatically git add the difference to the current commit (assuming we have a strong trust in our hooks)

**Comment by LMaxence** [comment]
This is fairly opinionated, but generally speaking, I would consider that a program modifying the code base during a hook is a bad practice, for the following reasons :

1. The hook user does not control the changes being performed, more specifically, **he can not review them easily since they are added to the staged files** 
2. I do think that hooks are just here for enforcement, and should not do the work that should have been done during development, whether it be running a linter wit `--fix` or have a editor properly configured. **Actually, hooks, when used only for changes are terribly efficient for detecting environment misconfigurations.**

Moreover, I don't think adding flags to the command are good enables for features, because the hooks are invoked through the `git` hooks scripts, and this part is automatically written for the user in the `init` command, *thus should be not have to be modified after.*

**On the other side**

I do agree, that fixing easily failing hooks is a big part of the comfort of use, hence I would propose the following modification : 

1. We add a `fix` option in the hook steps configuration, which would be a command to run to fix any failing hooks.
2. When a hook step fails, if there is a `fix` attribute in the step configuration, it is put into evidence for the user.

What about this ?
