### ISSUE TITLE
How do you submit a PR for this repo?

### ISSUE THREAD

**Issue by duereg** [Escape-Technologies/mookme#113]
I found some bugs/typos I want to resolve, but when I try to push my branch up to open a PR, I get permission denied. Do you not accept PRs?

**Comment by LMaxence** [comment]
Hello @duereg :) I'm really happy that you want to contribute, and I would happily accept any contribution that make this product go further !

It is not allowed to push new branches in the repository, but you can fork the repository and open a merge from a branch in the fork to the `beta` branch of this repository afterwards.

Here are more details on forks: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks

Feel free to add another comment if this doesn't answer your question, or if you need any more details, otherwise I'll close this issue in a day or two.
