### ISSUE TITLE
Step dependencies

### ISSUE THREAD

**Issue by MatthewScholefield** [Escape-Technologies/mookme#14]
Consider a typical set of hooks:
```json
{
  "type": "python",
  "venvActivate": ".venv/bin/activate",
  "steps": [
    {
      "name": "Format Code",
      "command": "blue ."
    },
    {
      "name": "Sort Imports",
      "command": "isort ."
    },
    {
      "name": "Ensure Style (flake8)",
      "command": "flake8 my_project"
    },
    {
      "name": "Ensure Style (pylint)",
      "command": "pylint my_project -E"
    }
  ]
}
```

This works great, however when the formatter fixes a long line, the linter still can complain about it because it seems like the linter is run in parallel. It would be nice to be able to specify dependencies or have a flag to label a step as something that could perform modifications so that they could be run serially. Something like:
```json
{
  "type": "python",
  "venvActivate": ".venv/bin/activate",
  "steps": [
    {
      "name": "Format Code",
      "command": "blue .",
      "serial": true
    },
    {
      "name": "Sort Imports",
      "command": "isort .",
      "serial": true
    },
    {
      "name": "Ensure Style (flake8)",
      "command": "flake8 my_project"
    },
    {
      "name": "Ensure Style (pylint)",
      "command": "pylint my_project -E"
    }
  ]
}
```

Which would force execution like:
```
Format Code -> Sort Imports -> Ensure Style (flake8)
                            -> Ensure Style (pylint)
```

**Comment by LMaxence** [comment]
I see, this is a legit request and indeed, steps are completely parallelized as of now. However, in the example you provided above, a few questions remain : 

- Do we have to wait for serial steps to be executed to run the non-serial ones ?
- What happens if a serial step fails ? Do we stop them all or keep execution going

So the way I see this, I would add a feature for serializing execution at the hook level (one level above the step level as you proposed) so that either we run everything in parallel, either everything is parallelized.

In any case, this will be a piece to get done, because the `hook-package` file, responsible for running the steps of a json hook file is completely built around the parallelization of steps. I'll need time if not help to have it correctly designed :)

**Comment by MatthewScholefield** [comment]
Just to drop in my thoughts: not sure what the best choices are in the general case, but I would guess that having some set of autoformatters followed by some set of linters/style checkers would be the most common case. So I'd imagine a good choice is whatever naming and behavior works well with the case of 2+ formatters and 2+ checkers.

**Comment by LMaxence** [comment]
Hey @MatthewScholefield ! 

Sorry for the delay, summer is here in Paris. I implemented something that might match your usage for the `serial` step option :) 

Feel free to review this

**Comment by LMaxence** [comment]
This has been release with 0.0.24 version :)
