### ISSUE TITLE
Fix `--only-hook[s]` typo

### ISSUE THREAD

**Issue by MatthewScholefield** [Escape-Technologies/mookme#15]
[The docs](https://mookme.org/get-started/#already-configured-project) say `--only-hooks` but the CLI and [reference docs](https://mookme.org/references/#options) use `--only-hook` .

I would create a PR but I'm not sure which one to use and how to regenerate the docs.

**Comment by LMaxence** [comment]
That's completely a mistake from me indeed !

I'm fixing this right now. In order to know which one to use, when there is a doubt, the information from the `mookme --help` are the most up-to-date since it is generated by commander (our CLI helper) itself. (it is `--only-hook`)

I did not have time yet to elaborate the contribution guide and developer's documentation but now that there is an external contributor this becomes critical, so I will address this ASAP.

In the meantime, the documentation is written in vuepress and stored under the `docs` package. If you intend to generate the documentation in your local environment, you just have to `cd` into that package, run `npm i` and then `npm run dev`.
I invite you to consult the documentation of Vuepress in order to have a better understanding of the structure of this package :)

**Comment by LMaxence** [comment]
You'll have it here : https://github.com/Escape-Technologies/mookme/pull/17
