### ISSUE TITLE
[Documentation] Improvements

### ISSUE THREAD

**Issue by iCarossio** [Escape-Technologies/mookme#33]
# Small typos

`args` is not between quotes

<img width="794" alt="Screenshot 2021-11-02 at 10 15 30" src="https://user-images.githubusercontent.com/15650113/139822053-6d331b99-00dd-4124-9b1d-9640b989db3d.png">

`pylint-changed-files` is in fact `python-changed-files` and `changed-files` is `python-changed-files` too.
<img width="828" alt="Screenshot 2021-11-02 at 10 15 15" src="https://user-images.githubusercontent.com/15650113/139822246-19a6438e-9cc7-4f49-b644-c832075f7538.png">

Plus the hierarchy tree is not clear.

# Misunderstandings

https://mookme.org/features/#reusable-steps
There is no example of "reusable-step" so we don't know if we should put 1 step per file, multiple steps in a list, or in a "steps" key… ?

# Example issues

This script does not work on Mac.

```bash
#!/usr/bin/env bash
git diff --cached --name-only --relative | while read line; do [ ! -f \"$line\" ] || printf \"%s\\n\" \"$line\"; done | grep -P '\\.py$' | xargs -d '\\n' $@
```

This one is way more elegant & works on both Max & Ubuntu:

```bash
#!/usr/bin/env bash
git --no-pager diff --cached --name-only --relative | perl -nle'print if m{.py$}' | xargs -n1 $@
```

**Comment by MatthewScholefield** [comment]
I'm not the owner of the project, but great feedback! Just wanted to add one more improvement to the example script:
```bash
#!/usr/bin/env bash
git --no-pager diff --cached --name-only --diff-filter=AM --relative -- "***.py" | tr '\n' '\0' | xargs -0 "$@"
```
Or if we want it to be completely generic (ie. `changed-files` instead of `python-changed-files`):
```bash
#!/usr/bin/env bash

sex -ue

file_filter=$1
shift

git --no-pager diff --cached --name-only --diff-filter=AM --relative -- "$file_filter"" | tr '\n' '\0' | xargs -0 "$@"
```

Anyways, I know that a PR with all these improvements would definitely be welcome. You should be able to run the docs locally with `cd packages/docs && npm install && npm run dev`.

Also, I just tested it out and the format shared hooks is a single top level json formatted the same as a hook. For example:
```python
# /.hooks/shared/flake8.json
{
  "name": "Ensure Style (flake8)",
  "command": "flake8 $(python-module) --ignore E203,W503 --max-line-length 90",
  "onlyOn": "**/*.py"
}
```
(Notice how you can use partials like in this example `python-module` within the shared hooks)

**Comment by MatthewScholefield** [comment]
(Oh whoops lol didn't realize you were part of the project xD. My bad for speaking to you like a new user lol)

**Comment by LMaxence** [comment]
In fact, it is nice to have the sharing features explicitely documented somewhere, but we could also use have used the `Recipes` section of the docs to provide more examples of this. I'm especially thinking about NodeJS examples or other languages examples.

I would love to have a way of getting some feedbacks on how people use Mookme in their projects, so that we could improve this section !
