### ISSUE TITLE
Document array of matching expressions for onlyOn configuration property

### ISSUE THREAD

**Issue by lstrojny** [Escape-Technologies/mookme#60]
`onlyOn` either by accident or consciously support passing an array of matching expressions. Probably worth mentioning that in the documentation.
This happy coincidence allows me to work around https://github.com/Escape-Technologies/mookme/issues/59

**Comment by LMaxence** [comment]
Hello !

Actually, is totally fortunate but yes a list of string can be passed in the `onlyOn` option. I just realized it here but it is due to 2 things:
- TypeScript/JavaScript does not perform any type checking at runtime, so if you write an array in a `string` typed reference, well, it won't be noticed until it raises an error.
- [wildcard-match](https://www.npmjs.com/package/wildcard-match), the library I use for doing the pattern matching actually supports being provided with an array of strings

From here, I see two things to do:
1. Fix the documentation indeed, so that it is documented that you can use a list of strings
2. Find a way to improve this system as you mentioned it in #59 (I'll document it on this issue)

Let's keep this open for the first point :)

I'm a bit late on documenting how to contribute to the docs (and to the project in general but it's definitely my next up thing to do on Mookme !). It's nothing more than a common [vuepress](https://vuepress.vuejs.org/) project.

You'll want to update the file located in `docs/references/README.md` which describes the `onlyOn` option.

Otherwise I'll leave it open and fix this at some but it's a very good first issue for eventual contributors :)
