### ISSUE TITLE
Expand inspect to test for a specific file

### ISSUE THREAD

**Issue by lstrojny** [Escape-Technologies/mookme#62]
`mookme inspect` gives a great overview of all the configured hooks. It would be terrific if I could pass one or more files to test which hooks would be run should those files change.

Something like:
```
$ npx mookme inspect -t pre-commit some-project/foo/bar.js
…
```

**Comment by LMaxence** [comment]
Great idea ! And actually another great first issue I think. I completely approve this and will document a strategy in the weekend :)

Same as your issue on the documentation, once it is specified, if anyone wants to add a contribution for this it will be warmly welcome otherwise I'll come up with an implementation a bit later

**Comment by LMaxence** [comment]
Here is the spec for this

# Description

We want to add a CLI option to the `inspect`command, for selecting which files of the codebase to inspect. Ie, detect which hooks are triggered for a specific file. I think this list should be an optional argument as @lstrojny described it :)

# Todos

1. Filter the inspected hooks based on this list of files if it is provided
[] First, we have to update the command definition in `src/commands/inspect.ts` so that it can read a list of files.
[] We'll have to refacto `HooksResolver` class, so that `filterWithVCS` calls another method `filterWithFiles` after retrieving the VCS state.
[] Then, in the class `InspectRunner`, we can call directly `filterWithFiles` with the list of provided files if it is provided.

2. Handle the `onlyOn` case
[] As of now, onlyOn is evaluated in the step-executor, so it might be tricky to use it in the inspect command directly. One thing we can do, is to instanciate a `StepExecutor` for each step we retrieve, using the list of files if provided, and look into it's `skipped` property.

Definitely not a good first issue finally ! I'll take a look into this when I get time during next week :) . If you feel to come up with an implementation before, it would naturally be welcome

**Comment by LMaxence** [comment]
I wrote the resolver strategy for this use case and applied it in `inspect` if desired, you can either test the branch or I'll merge and deploy it in beta tonight :)
