### ISSUE TITLE
Filter hooks via file extension / file type

### ISSUE THREAD

**Issue by iCarossio** [Escape-Technologies/mookme#8]
In the same repo, some hooks are checking only some kinds of files.
For instance, if I modify a Markdown I don't necessarily want that the hook formatting Python files runs uselessly.

Thus would be great to have an option like `files`, `fileType` or `fileExtension` (or anything else) so that the hook only run if that files of that kind have changed :)

This would optimise the run time too!

Example:
```json
    {
        "name": "yapf",
        "command": "yapf -ri escape_scanner tests",
        "files": [".py"]
    }, 
```

**Comment by LMaxence** [comment]
Hey :)

I have the feeling that what you describe here should be determined by the hook command. We could definitely add such a feature in `mookme`, but that would probably be overkill and misleading for the following reasons : 

- most modern linters implement their way to run only against staged files
- more specifically, it is possible in a given directory to list the files that have been changed and match a specific extension

In your case, to find `*.py` files changed in the package `mypackage`, you would cd into that package (good news, mookme already performs that the current working directory is scoped by package :) ) and run `git diff --name-only --relative  --cached --diff-filter=AM -- './**/*.py'`

- The former becomes very handful when you have a linter or formatter that accept list of files or folders
In the case of yapf, your probleme could be solved by changing your hook from 

`yapf -ri escape_scanner tests`

to 

`yapf -ri $(git diff --name-only --relative  --cached --diff-filter=AM -- './tests/**.py' './escape_scanner/**.py')`

If you wanna understand the `git diff` command : 

- --name-only -> only the name of the files
- --relative -> relative path
- --cached -> only staged files
- --diff-filter=AM -> only added or modified files
- -- './tests/**.py' './escape_scanner/**.py' -> only files that match './tests/**.py' or './escape_scanner/**.py

**Comment by iCarossio** [comment]
Hello,
I don’t understand the workaround but I see at least 2 issues here:

1) In my opinion `yapf -ri $(git diff --name-only --relative --cached --diff-filter=AM -- './tests/**.py' './escape_scanner/**.py')`  feels way more confusing than
- `cmd: yapf -ri escape_scanner tests`
- ˋfiles: .py`

2) This means that even if I have a just modified Markdown file the Python formatter will start in the repo in order to understand it has to format nothing… A bit like if you were giving your math exam to your history teacher that would say « It’s okay for me! » because in fact it’s not his role to correct a math exam.


But I think the philosophical issue behind this is the same as my first enhancement proposal.
Either you consider MookMe as a « hook trigger » or a « hook manager ».

And I think that `pre-commit` is a horrible « hook trigger », especially for Monorepo, and you definitely killed it in less than 1 week of work on that point.
However I think ˋpre-commit` remains a « hook manager » with a lot of relevant and productive options. I did not say it was good but at least tunable and some options are definitely cool. It could be possible to kill it on that side too :)

And maybe adding a `file` key **is not** the best option to make MookMe better than pre-commit on hook management.

**Comment by LMaxence** [comment]
I have two concerns here :

- the more we'll try to be a copy of pre-commit, the more we'll encounter the same pledges and drawbacks
- the more feature and options we provide, and thus move aside from the **minimalistic** approach of mookme on the question of git hooks, the more features we'll to support and maintain, including compatibility assesment.

This second point is the only reason why I am heavily discussing any feature request, I do not say it is not a good idea, I just want to make perfectly sure that it is a move forward for the tool.

But I agree it could be nice to have some more management options and hook optimization, would it be possible for you to provide a poc of this so that I can wrap my head around how deep it would alter already existing filters, and how it would operate with them ?

The way I see this it should be at the step level, so each step of a given hook JSON file could have a `onlyOn` option that will be a regular expression.

On a given step, if this option is present, the step will be executed only if there is at least one staged file matching this regular expression.

En vrac :

- beware that diff are retrieved with absolute path unless we tell git to ;)
- let's at least have a warning telling the step is skipped because no file matched in place of the running.... -> success / failed logger

**Comment by LMaxence** [comment]
Proposal in https://github.com/Escape-Technologies/mookme/pull/9

**Comment by LMaxence** [comment]
I'm closing this since it has been implemented
