### ISSUE TITLE
pre-push hook works only if triggered from the package it's written for, but isn't fired from root

### ISSUE THREAD

**Issue by bdvorianov-sapient** [Escape-Technologies/mookme#81]
### Discussed in https://github.com/Escape-Technologies/mookme/discussions/79

<div type='discussions-op-text'>

<sup>Originally posted by **bdvorianov** April  8, 2022</sup>
Imagine we have a structure like:

+ rootFolder
  + .hooks
  + package
    + .hooks
      + pre-commit.json
      
In such case, pre-commit will be fired only if `git commit` was fired from the `package` directory, but it seems kinda natural that it may be fired when `commit` was fired from the `rootFolder` and we have staged changes in `package`. I see global hook with `onlyOn` as a solution, but it's not as clean as if it would work as above. Is there a way to do this? 🤔

Pre-commit works as described, but not pre-push. So when I push from rootFolder it doesn't work, but when I change directory to package and push from there it works as expected. I'm not sure, but maybe it's issue specific to pre-push.</div>

**Comment by bdvorianov-sapient** [comment]
@LMaxence where should I create a repo with example setup?

**Comment by LMaxence** [comment]
Hello @bdvorianov-sapient !

Sorry for the delay, you can create an example (public) repository on your own Github and post the link here :) 

I'm sort of in a rush right now, and days are too short for me to immediately solve this, but I will get down to it once things get a bit calmer. Truly sorry for that ! If it takes too much time, you can also open a merge reques solving this. I'll be happy to review it in the shortest notice

**Comment by mhozhynewscorp** [comment]
Hey @LMaxence 
I'm here with the same issue.
Tests are never run from the repo root, but are run if you push changes from a package with `.hooks`.
I have such hook

```json5
// ./packages/package-a/.hooks/pre-push.json
{
  "steps": [
    {
      "name": "Run tests",
      "command": "npm run test"
    }
  ]
}
```
I kind of guess why it doesn't work, it's just that I've already tried the `lint-staged` + `mookme` setup.

It's just that if you declare it as 

`npm run eslintfix`, the parameters don't go into the command.

But this is a slightly different case here. I don't need parameters (on the other hand I'm sure it's very easy to come up with a case where you need a list of files). I just need to figure out how to call the hook(s) from the folder(s) that are changed by dying all the affected files from the commits I send.

Any tips would be greatly appreciated

**Comment by mhozhynewscorp** [comment]
there is sample repository https://github.com/mhozhynewscorp/mookme-pre-push

Seems that only global pre-push hook is working, when I deleted it I was able to push anything although tests returns `exit 1`
What's more interesting I don't see messages from `echo` even for `pre-commit`
It's definitely isn't working I mean `pre-push`

**Comment by mhozhynewscorp** [comment]
>  What's more interesting I don't see messages from echo even for pre-commit
`pre-commit` seems just ignoring `stdout`

**Comment by LMaxence** [comment]
Hello @mhozhynewscorp,

The `pre-push` hook is quite recent, and I would currently hold it as a work in progress, as I do not have an extensive usage of this one on my side, and I try to improve it along the issues that people open. I'll just ask you to bear with me while we make something cool out of it !

The strategy used by this hook to decide what steps to run is based on the files changed in the commits of your current branch that have not been pushed. Or at least it should be. From what I see in your messages there is definitely something weird going on here. I'll look into it asap

Regarding `stdout`:
- It's a desired feature to not print the content of the stdout, or at least it's the way I designed it.
- I am surely not closed to any suggestion on this, yet my current line is "I don't care of the log when everything is fine, I just want them when something went wrong"

**Comment by LMaxence** [comment]
Hello :)

I took a proper look at your repository, and what I saw is that when running a pre-push hook, the strategy used to select the hooks to run isn't the one I described above, but the default `currentCommitStrategy`. So, it tries to select packages based on your staged files, but since you just commited, you would surely have.

> Seems that only global pre-push hook is working, when I deleted it I was able to push anything although tests returns exit 1

This is totally normal, because the global hooks are always executed. So if you have a global pre-push, it will always be fired. The problem here is that packages pre-push hooks are *never* fired (because of the wrong strategy being used).


Here is the debug log:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/29194680/168465114-3cefb1e0-2259-404e-bff6-3b0f9b890284.png">

Definitely a bug, thanks for pointing it out :)

A good fix for this would be to actually implement the strategy I mentioned above. When a `pre-push` hook is fired, we want to hook packages that are included in any commit not yet pushed.

I'll leave the implementation details here if you are willing to fix it yourself, otherwise I will work on this during the week.

- in `packages/mookme/src/loaders/filter-strategies` add a strategy `not-pushed-files-filter.ts` that implements a class `NotPushedFilesFilterStrategy` extending the `FilterStrategy` class. You can take the other strategies for example, but the main role of the strategies is to provide the list of files used to decide what hooks to run. For instance the case of the current commit strategy, it will simply return the list of staged files.

- Find a git command able to return the list of files changed between HEAD and the last pushed commit. Maybe that we can re-use the method `getFilesChangedBetweenRefs` in `git.ts`

- Implement the method `getFilesPathList` of the strategy using this command.

- Add the strategy in the constructor of the `HooksResolver` class (in `hooks-resolver.ts`). You just have to add a case in the switch statement of the constructor.

- If I structured Mookme correctly, it should be enough for the pre-push strategy to be implemented :)

**Comment by LMaxence** [comment]
Okay, so I started to work on this, and it seems to be a massive pain to retrieve the list of unpushed commits from git.

My current best candidate is `git rev-list ${push}..` which works really nice except when the current branch has not been pushed yet (no upstream).

For this case, I would like to find a way to retrieve the last commit sha pushed on the parent branch, but I couldn't find a good command for this so far.

This makes me think that [this project (nodegit) exists](https://github.com/nodegit/nodegit) and that we might find a solution in here, but I could not look into it so far

**Comment by mhozhynewscorp** [comment]
I guess we need to reopen @LMaxence

**Comment by bartekczyz** [comment]
I agree with @mhozhynewscorp, this is still an issue, but I saw it's been released in beta 2.2. Is it possible to cut a stable 2.2 release?

**Comment by LMaxence** [comment]
I just did, sorry for the delay, and let me know if that remains an issue !

**Comment by mhozhynewscorp** [comment]
> I just did, sorry for the delay, and let me know if that remains an issue !

I'll check soon

**Comment by mhozhynewscorp** [comment]
So, no changes in buggy behaviour @LMaxence 
tested with `2.2.0`

**Comment by mhozhynewscorp** [comment]
@LMaxence 
maybe it will be usable
I remember you don't have any glue which commands to use to get list of the changes


https://github.com/evilmartians/lefthook/issues/302#issuecomment-1194344242

please consider that on push always exist 2 cases:
- new branch
- existing branch

But for now we can only conclude that this is not just a bug under some circumstances, it's almost entirely not working hook.
Most likely it is just not used by the audience. 

**Wouldn't it be easier to delete the mention of support for this hook?**

**Comment by sethmbrown** [comment]
Is this hook unsupported? As of v2.3.0 is still appears to be not working. Thanks!

**Comment by bashirsouid** [comment]
+1 not working for me either after struggling with it a while but alas no dice.
