### ISSUE TITLE
Using mookme as postinstall script

### ISSUE THREAD

**Issue by c3b5aw** [Escape-Technologies/mookme#98]
Hello @LMaxence,

Did you considered recommendation of `postinstall` script to setup mookme when using yarn v2 ?
I got this idea from [husky](https://typicode.github.io/husky/#/?id=yarn-2).
You have any objection to this kind of usage?

**Comment by c3b5aw** [comment]
Refer to [118](https://github.com/Escape-Technologies/graphql-armor/pull/118)

**Comment by LMaxence** [comment]
Hey @c3b5aw !

That could indeed be a good simplification of how mookme is setup, by removing one command to run.

However, I am not sure that postinstall scripts are the solution we are looking for.

The first reason is that, generally speaking, postinstall script are too expensive in terms of maintenance and risk of bugs occuring, compared to the value they bring into the package.

[Yarn istelf advises against, for reasons that I personally agree with.](https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall)

Regarding what you did in graphql-armor, it will work. However, depending on if mookme is asked as a dev dependency or a normal dependency, you might be asking anyone that installs gql-armor to run a mookme init somehow. I know you probably specified mookme as the correct type of dependency, but that is the kind of issue that could occur.

Essentially, this approach would delegate the core part of mookme's setup to the package manager, which, in my opinion, cannot be trusted for this. This is mainly due to the strong variety of package managers and their numerous versions in activity.

Finally, I like the idea of bringing a light to the average user on how git hooks are defined in the git folder, and how they work.

For all these reasons, I would generally not incline for using postinstall scripts, sorry :/

**Comment by c3b5aw** [comment]
Thanks you.

For educational I found this blog post from husky: https://blog.typicode.com/husky-git-hooks-autoinstall/
